import matplotlib
# Force backend to non-interactive (Prevents Server Crashes)
matplotlib.use('Agg') 
import matplotlib.pyplot as plt
from fpdf import FPDF
import os
import numpy as np

# --- CONFIGURATION ---
COMPANY_NAME = "STRESS SIGNAL"
REPORT_TITLE = "CLINICAL STRESS ANALYSIS"
ACCENT_COLOR = (0, 51, 102)     # Deep Navy Blue
SECONDARY_COLOR = (0, 153, 153) # Teal
TEXT_COLOR = (50, 50, 50)       # Dark Grey

def clean_text(text):
    """Sanitizes text to prevent PDF generation crashes."""
    if not isinstance(text, str): return str(text)
    replacements = {"\u2018": "'", "\u2019": "'", "\u201c": '"', "\u201d": '"', "\u2013": "-"}
    for k, v in replacements.items(): text = text.replace(k, v)
    return text.encode('latin-1', 'replace').decode('latin-1')

class MedicalReport(FPDF):
    def header(self):
        # --- 1. PROFESSIONAL TOP BAR ---
        self.set_fill_color(*ACCENT_COLOR)
        self.rect(0, 0, 210, 25, 'F') # Increased height slightly for logo
        
        # --- 2. DRAW ECG ICON (White) ---
        self.set_draw_color(255, 255, 255) # White lines
        self.set_line_width(0.8)
        
        # Icon Position (Top Left)
        start_x = 10
        base_y = 12.5 # Center of header
        
        # Drawing the Pulse: Flat -> Up -> Down -> Up -> Flat
        # Coordinates relative to start_x, base_y
        self.line(start_x, base_y, start_x+3, base_y)             # Flat
        self.line(start_x+3, base_y, start_x+4, base_y-3)         # Small Up
        self.line(start_x+4, base_y-3, start_x+5, base_y+4)       # Down
        self.line(start_x+5, base_y+4, start_x+7, base_y-6)       # Big Spike Up
        self.line(start_x+7, base_y-6, start_x+9, base_y+2)       # Down
        self.line(start_x+9, base_y+2, start_x+12, base_y)        # Flat
        
        # --- 3. COMPANY TITLE ---
        self.set_font('Helvetica', 'B', 18)
        self.set_text_color(255, 255, 255)
        # Move text to the right of the icon
        self.set_xy(25, 6) 
        self.cell(0, 10, clean_text(COMPANY_NAME), 0, 0, 'L')
        
        # --- 4. SUBTITLE ---
        self.set_font('Helvetica', '', 9)
        self.set_text_color(200, 200, 200) # Light Grey
        self.set_xy(25, 13)
        self.cell(0, 6, "Advanced Optical Stress Monitoring System", 0, 0, 'L')
        
        self.ln(20) # Space after header

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Generated by Stress Signal AI - Clinical Use Disclaimer - Page {self.page_no()}', 0, 0, 'C')

def create_stress_graph(stress_value, bpm_value, filename):
    try:
        # Compact graph to fit perfectly on one page
        plt.figure(figsize=(8, 2.5)) 
        x = np.linspace(0, 60, 60)
        noise = np.random.normal(0, 1.5, 60)
        y = np.linspace(stress_value - 10, stress_value, 60) + noise
        y = np.clip(y, 0, 100) 

        # Background Zones
        plt.axhspan(0, 40, facecolor='#e6ffe6', alpha=1)   # Green
        plt.axhspan(40, 70, facecolor='#ffffe6', alpha=1)  # Yellow
        plt.axhspan(70, 100, facecolor='#ffe6e6', alpha=1) # Red

        # Plot Line
        plt.plot(x, y, color='#003366', linewidth=2)
        
        # Highlight Final Point
        plt.scatter(60, stress_value, color='#cc0000', s=40, zorder=5)
        plt.text(55, stress_value + 8, f"{int(stress_value)}%", fontsize=8, color='#cc0000', fontweight='bold')

        # Styling
        plt.title(f"Session Stress Variation (60s) | Avg BPM: {int(bpm_value)}", fontsize=9, fontweight='bold', color='#333333')
        plt.ylabel("Stress (%)", fontsize=7)
        plt.xlabel("Time (s)", fontsize=7)
        plt.ylim(0, 100)
        plt.xticks(fontsize=7)
        plt.yticks(fontsize=7)
        plt.grid(color='gray', linestyle=':', linewidth=0.5, alpha=0.5)
        
        # Remove borders for clean look
        plt.gca().spines['top'].set_visible(False)
        plt.gca().spines['right'].set_visible(False)
        
        plt.tight_layout()
        plt.savefig(filename, dpi=300, bbox_inches='tight')
    except: pass
    finally: plt.close('all')

def generate_pdf(user_name, bpm, stress, analysis_result, date):
    pdf = MedicalReport()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # --- 1. PATIENT INFO BOX (Grey Box) ---
    pdf.set_fill_color(248, 248, 248) # Very light grey
    pdf.set_draw_color(220, 220, 220)
    pdf.rect(10, 30, 190, 20, 'FD') # Moved down slightly to clear larger header
    
    pdf.set_y(33)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(*TEXT_COLOR)
    
    # Left Column
    pdf.set_x(15)
    pdf.cell(25, 5, "PATIENT:", 0, 0)
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(60, 5, clean_text(user_name), 0, 0)
    
    # Right Column
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(25, 5, "DATE:", 0, 0)
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(50, 5, clean_text(date), 0, 1)
    
    # Row 2
    pdf.set_x(15)
    pdf.ln(6)
    pdf.set_x(15)
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(25, 5, "SESSION ID:", 0, 0)
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(60, 5, f"#{abs(hash(date)) % 100000:06d}", 0, 0)
    
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(25, 5, "MODE:", 0, 0)
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(50, 5, "Live Optical Sensor", 0, 1)
    
    pdf.ln(15)

    # --- 2. VITALS CARDS (3-Card Layout) ---
    y_pos = pdf.get_y()
    card_width = 60
    card_height = 18
    
    # BPM CARD (Blue)
    pdf.set_fill_color(235, 245, 255) 
    pdf.rect(10, y_pos, card_width, card_height, 'F')
    pdf.set_xy(10, y_pos + 3)
    pdf.set_font("Helvetica", "B", 8)
    pdf.cell(card_width, 4, "HEART RATE", 0, 2, 'C')
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(*ACCENT_COLOR)
    pdf.cell(card_width, 6, f"{int(bpm)} BPM", 0, 0, 'C')
    
    # STRESS CARD (Red/Orange)
    pdf.set_text_color(*TEXT_COLOR)
    pdf.set_fill_color(255, 240, 235)
    pdf.rect(75, y_pos, card_width, card_height, 'F')
    pdf.set_xy(75, y_pos + 3)
    pdf.set_font("Helvetica", "B", 8)
    pdf.cell(card_width, 4, "STRESS LEVEL", 0, 2, 'C')
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(200, 50, 50)
    pdf.cell(card_width, 6, f"{int(stress)} %", 0, 0, 'C')

    # STATUS CARD (Green)
    pdf.set_text_color(*TEXT_COLOR)
    pdf.set_fill_color(235, 250, 235)
    pdf.rect(140, y_pos, card_width, card_height, 'F')
    pdf.set_xy(140, y_pos + 3)
    pdf.set_font("Helvetica", "B", 8)
    pdf.cell(card_width, 4, "STATUS", 0, 2, 'C')
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(0, 100, 0)
    status_text = "NORMAL" if stress < 60 else ("ELEVATED" if stress < 80 else "HIGH")
    pdf.cell(card_width, 6, status_text, 0, 0, 'C')
    
    pdf.ln(25)

    # --- 3. GRAPH SECTION ---
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*SECONDARY_COLOR)
    pdf.cell(0, 8, "SESSION VISUALIZATION", 0, 1)
    
    graph_filename = f"temp_graph_{date}.png"
    create_stress_graph(stress, bpm, graph_filename)
    if os.path.exists(graph_filename):
        pdf.image(graph_filename, x=10, w=190)
        try: os.remove(graph_filename)
        except: pass
    pdf.ln(5)

    # --- 4. ANALYSIS TEXT ---
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*SECONDARY_COLOR)
    pdf.cell(0, 8, "AI CLINICAL ASSESSMENT", 0, 1)
    
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(50, 50, 50)
    pdf.multi_cell(0, 5, clean_text(analysis_result['message']))
    pdf.ln(5)

    # --- 5. RECOMMENDATION BOX (Green Box) ---
    pdf.set_fill_color(240, 255, 240) # Light Green
    pdf.set_draw_color(100, 180, 100)
    pdf.rect(10, pdf.get_y(), 190, 15, 'FD')
    
    current_y = pdf.get_y()
    pdf.set_xy(15, current_y + 4)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(0, 100, 0)
    pdf.cell(35, 5, "RECOMMENDATION:", 0, 0)
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(0, 5, "Maintain regular breathing. Continue monitoring if stress persists.", 0, 1)

    filename = f"report_{date}.pdf"
    full_path = os.path.join("reports", filename)
    if not os.path.exists("reports"): os.makedirs("reports")
    pdf.output(full_path)
    return full_path